### ISSUE TITLE
WACCAスコアツール(仮)について

### ISSUE THREAD

**Issue by mikist0326** [NAOseryu/NAOseryu.github.io#5]
今回githubを使うのが初めてなので、拙い所、見苦しい所があるかもしれません。
いきなり突然ですみません。いつもwaccaスコアツールを愛用していますmikistと申します。
今回は上記のスコアツールで閲覧出来る平均スコアとスコア閲覧についてです。
平均スコアについて、eden、Silentphobia から始まり、EPHMR、DANGEROOOOUS JUNGLE、Dimension Hacker、クリムゾン帝王、神のINFERNOはあるのですが、EXPERTの平均スコアが無いので追加をして欲しいです。
また、最近のアップデートで収録されたインフレリミックス、ジェノサイダーリミックスのEXPERT、更にMöbiusのEXPERTとINFERNOの追加もお願いしたいです。
スコア閲覧に関しては、上記のほぼ全てが追加されているのですが、レベルの関係かMöbiusのINFERNOが閲覧出来ない状況になっています。
なおさんも忙しい中大変かと思いますが、早めの返信及び対応をお願い出来ればと思います。

**Comment by NAOseryu** [comment]
@mikist0326
連絡ありがとうございます:bow:
EXPERTの平均スコアが無いのは集計する処理の不具合でした、修正したので現在は表示されているかと思います。
レベル15にも対応したのでMöbiusのINFERNOも表示されるようになっているかと思います。
また何かありましたら連絡いただけると助かります:pray:
